### PR TITLE
Add test-ca and test certs for riakuser and riak-test server

### PR DESCRIPTION
**Pull request by lukebakken**
In JURA: `CLIENTS-142`, `CLIENTS-143`

### CODE REVIEW

**Comment by lukebakken** [comment]
@alexmoore ready for review. FYI add `?w=1` to the URL when reviewing the diffs on GH to skip my whitespace changes. Other Basho shell scripts use 4-space indent.

**Comment by alexmoore** [comment]
https://github.com/basho-labs/CorrugatedIron/blob/jira/lrb/clients-142/tools/riak-cluster-config#L43 will generate an error if security is turned on: 

`Security is enabled and Riak does not accept credentials over HTTP. Try HTTPS instead.`

**Comment by lukebakken** [comment]
Good catch on that error.

**Comment by lukebakken** [comment]
@alexmoore all set

**Comment by alexmoore** [comment]
+1 :shipit:

**Pull request merged**
